"""
Focused regression tests for follow-up review fixes in xts_compare.
"""

from __future__ import annotations

import io
import json
import shutil
import sys
import tarfile
import tempfile
import unittest
import warnings
import zipfile
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from arkui_xts_selector.xts_compare.cli import _run_compare, build_parser, main
from arkui_xts_selector.xts_compare.compare import classify_transition, compare_runs, compute_module_health
from arkui_xts_selector.xts_compare.format_terminal import format_report
from arkui_xts_selector.xts_compare.models import FailureType, ModuleComparison, TestIdentity, TestOutcome, TestResult, TransitionKind
from arkui_xts_selector.xts_compare.parse import discover_archives, load_run, open_archive
from arkui_xts_selector.xts_compare.selector_integration import correlate_with_selector


def _make_result(module: str, suite: str, case: str, outcome: TestOutcome, msg: str = "") -> TestResult:
    return TestResult(
        identity=TestIdentity(module=module, suite=suite, case=case),
        outcome=outcome,
        message=msg,
    )


def _make_run(results: list[TestResult]):
    result_map = {result.identity: result for result in results}
    pass_count = sum(1 for result in result_map.values() if result.outcome == TestOutcome.PASS)
    fail_count = sum(1 for result in result_map.values() if result.outcome == TestOutcome.FAIL)
    blocked_count = sum(1 for result in result_map.values() if result.outcome == TestOutcome.BLOCKED)
    from arkui_xts_selector.xts_compare.models import RunMetadata

    return RunMetadata(
        label="run",
        total_tests=len(result_map),
        pass_count=pass_count,
        fail_count=fail_count,
        blocked_count=blocked_count,
    ), result_map


def _write_valid_summary_xml(path: Path) -> None:
    path.write_text(
        """<testsuites name="ActsSample">
<testsuite name="Suite">
  <testcase name="case1" status="run" result="true" time="0.1" />
</testsuite>
</testsuites>
""",
        encoding="utf-8",
    )


def _make_zip_report(path: Path) -> None:
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr(
            "summary_report.xml",
            """<testsuites name="ActsZip">
<testsuite name="Suite">
  <testcase name="case1" status="run" result="true" time="0.1" />
</testsuite>
</testsuites>
""",
        )


def _make_tar_report(path: Path) -> None:
    tmp = tempfile.mkdtemp()
    try:
        report_root = Path(tmp) / "report"
        report_root.mkdir()
        _write_valid_summary_xml(report_root / "summary_report.xml")
        with tarfile.open(path, "w:gz") as archive:
            archive.add(report_root / "summary_report.xml", arcname="summary_report.xml")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


class SecurityRegressionTests(unittest.TestCase):
    def test_load_run_rejects_path_traversal_in_log_refs(self):
        tmp = tempfile.mkdtemp()
        try:
            archive_dir = Path(tmp) / "archive"
            archive_dir.mkdir()
            secret_dir = Path(tmp) / "secret"
            secret_dir.mkdir()

            (archive_dir / "summary_report.xml").write_text(
                """<testsuites name="ActsCrashTest">
<testsuite name="CrashSuite">
  <testcase name="case1" status="run" result="false" />
</testsuite>
</testsuites>
""",
                encoding="utf-8",
            )
            static_dir = archive_dir / "static"
            static_dir.mkdir()
            (static_dir / "data.js").write_text(
                "window.reportData = "
                + json.dumps(
                    {
                        "modules": [
                            {
                                "name": "ActsCrashTest",
                                "error": "App died",
                                "logs": {
                                    "crash_log": "../secret/cppcrash.log",
                                },
                            }
                        ]
                    }
                )
                + ";",
                encoding="utf-8",
            )
            (secret_dir / "cppcrash.log").write_text(
                "Generated by HiviewDFX@OpenHarmony\nReason:Signal:SIGSEGV(SEGV_MAPERR)@0x1\n",
                encoding="utf-8",
            )

            meta, _results = load_run(str(archive_dir))
            self.assertIn("ActsCrashTest", meta.module_infos)
            self.assertIsNone(meta.module_infos["ActsCrashTest"].crash_info)
        finally:
            shutil.rmtree(tmp, ignore_errors=True)


class PhaseOneLogicTests(unittest.TestCase):
    def test_compute_module_health_counts_unblocked_as_positive(self):
        module = ModuleComparison(
            module="ActsModule",
            counts={
                TransitionKind.UNBLOCKED.value: 3,
            },
        )
        self.assertAlmostEqual(compute_module_health(module), 100.0, places=1)

    def test_selector_correlation_unblocked_does_not_report_no_change(self):
        base_meta, base_results = _make_run(
            [_make_result("ActsButtonTest", "ButtonSuite", "case1", TestOutcome.BLOCKED)]
        )
        target_meta, target_results = _make_run(
            [_make_result("ActsButtonTest", "ButtonSuite", "case1", TestOutcome.PASS)]
        )
        report = compare_runs(base_meta, base_results, target_meta, target_results)
        selector_report = {
            "results": [
                {
                    "changed_file": "frameworks/core/components/button/button_pattern.cpp",
                    "projects": [
                        {
                            "project": "test/xts/acts/arkui/ace_ets_component_button_static",
                            "score": 10,
                            "confidence": "high",
                            "bucket": "must-run",
                            "variant": "static",
                        }
                    ],
                }
            ]
        }

        correlations = correlate_with_selector(report, selector_report)
        self.assertEqual(len(correlations), 1)
        self.assertFalse(correlations[0].predicted_projects[0].predicted_but_no_change)

    def test_blocked_to_fail_is_new_fail(self):
        transition = classify_transition(
            _make_result("M", "S", "C", TestOutcome.BLOCKED),
            _make_result("M", "S", "C", TestOutcome.FAIL),
        )
        self.assertEqual(transition, TransitionKind.NEW_FAIL)

    def test_blocked_to_blocked_is_stable_blocked(self):
        transition = classify_transition(
            _make_result("M", "S", "C", TestOutcome.BLOCKED),
            _make_result("M", "S", "C", TestOutcome.BLOCKED),
        )
        self.assertEqual(transition, TransitionKind.STABLE_BLOCKED)


class CliErrorHandlingTests(unittest.TestCase):
    def setUp(self):
        self.parser = build_parser()

    def test_run_compare_handles_xml_parse_error(self):
        tmp = tempfile.mkdtemp()
        try:
            base_dir = Path(tmp) / "base"
            target_dir = Path(tmp) / "target"
            base_dir.mkdir()
            target_dir.mkdir()
            (base_dir / "summary_report.xml").write_text("<testsuites>", encoding="utf-8")
            (target_dir / "summary_report.xml").write_text(
                """<testsuites name="ActsTarget">
<testsuite name="Suite">
  <testcase name="case1" status="run" result="true" />
</testsuite>
</testsuites>
""",
                encoding="utf-8",
            )

            args = self.parser.parse_args(["--base", str(base_dir), "--target", str(target_dir)])
            with mock.patch("sys.stderr", new=io.StringIO()) as stderr:
                code = _run_compare(args)
            self.assertEqual(code, 2)
            self.assertIn("error loading run:", stderr.getvalue())
        finally:
            shutil.rmtree(tmp, ignore_errors=True)


class PhaseTwoCliTests(unittest.TestCase):
    def setUp(self):
        self.parser = build_parser()

    def test_parser_accepts_positional_compare_paths(self):
        args = self.parser.parse_args(["a.zip", "b.zip"])
        self.assertEqual(args.paths, ["a.zip", "b.zip"])
        self.assertIsNone(args.base)
        self.assertIsNone(args.timeline)

    def test_parser_accepts_short_output_flag(self):
        args = self.parser.parse_args(["a.zip", "b.zip", "-o", "report.json"])
        self.assertEqual(args.output, "report.json")

    def test_main_infers_html_from_output_suffix(self):
        tmp = tempfile.mkdtemp()
        try:
            base_dir = Path(tmp) / "2025-12-11-17-10-38"
            target_dir = Path(tmp) / "2025-12-25-16-48-38"
            base_dir.mkdir()
            target_dir.mkdir()
            _write_valid_summary_xml(base_dir / "summary_report.xml")
            _write_valid_summary_xml(target_dir / "summary_report.xml")
            output_path = Path(tmp) / "report.html"

            with mock.patch("sys.stdout", new=io.StringIO()), mock.patch("sys.stderr", new=io.StringIO()):
                code = main([str(base_dir), str(target_dir), "-o", str(output_path)])

            self.assertEqual(code, 0)
            self.assertTrue(output_path.is_file())
            self.assertIn("<!doctype html>", output_path.read_text(encoding="utf-8").lower())
        finally:
            shutil.rmtree(tmp, ignore_errors=True)


class PhaseThreeTests(unittest.TestCase):
    def setUp(self):
        self.parser = build_parser()

    def test_load_run_supports_tar_gz_archives(self):
        tmp = tempfile.mkdtemp()
        try:
            archive = Path(tmp) / "2026-01-15-10-00-00.tar.gz"
            _make_tar_report(archive)
            meta, results = load_run(str(archive))
            self.assertEqual(meta.total_tests, 1)
            self.assertEqual(len(results), 1)
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_discover_archives_returns_sorted_supported_archives(self):
        tmp = tempfile.mkdtemp()
        try:
            older = Path(tmp) / "2025-12-11-17-10-38.zip"
            newer = Path(tmp) / "2025-12-25-16-48-38.tar.gz"
            _make_zip_report(older)
            _make_tar_report(newer)

            discovered = discover_archives(tmp)
            self.assertEqual(discovered, [str(older), str(newer)])
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_directory_scan_two_archives_enters_compare_mode(self):
        tmp = tempfile.mkdtemp()
        try:
            scan_dir = Path(tmp) / "runs"
            scan_dir.mkdir()
            older = scan_dir / "2025-12-11-17-10-38.zip"
            newer = scan_dir / "2025-12-25-16-48-38.zip"
            _make_zip_report(older)
            _make_zip_report(newer)

            stdout = io.StringIO()
            stderr = io.StringIO()
            with mock.patch("sys.stdout", new=stdout), mock.patch("sys.stderr", new=stderr):
                code = main([str(scan_dir)])

            self.assertEqual(code, 0)
            self.assertIn("Entering compare mode", stderr.getvalue())
            self.assertIn("XTS Compare", stdout.getvalue())
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_directory_scan_single_archive_enters_single_run_summary(self):
        tmp = tempfile.mkdtemp()
        try:
            scan_dir = Path(tmp) / "runs"
            scan_dir.mkdir()
            archive = scan_dir / "2026-01-15-10-00-00.zip"
            _make_zip_report(archive)

            stdout = io.StringIO()
            stderr = io.StringIO()
            with mock.patch("sys.stdout", new=stdout), mock.patch("sys.stderr", new=stderr):
                code = main([str(scan_dir)])

            self.assertEqual(code, 0)
            self.assertIn("Entering single-run summary mode", stderr.getvalue())
            self.assertIn("XTS Run Summary", stdout.getvalue())
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_run_compare_defaults_sort_to_severity_when_regressions_exist(self):
        base_meta, base_results = _make_run([_make_result("M", "S", "C", TestOutcome.PASS)])
        target_meta, target_results = _make_run([_make_result("M", "S", "C", TestOutcome.FAIL, "boom")])
        args = self.parser.parse_args(["--base", "base", "--target", "target"])

        with mock.patch("arkui_xts_selector.xts_compare.cli.load_run", side_effect=[(base_meta, base_results), (target_meta, target_results)]), \
                mock.patch("arkui_xts_selector.xts_compare.cli.format_report", return_value="ok") as format_report_mock, \
                mock.patch("sys.stdout", new=io.StringIO()):
            code = _run_compare(args)

        self.assertEqual(code, 1)
        self.assertEqual(format_report_mock.call_args.kwargs["sort_key"], "severity")

    def test_run_compare_auto_enables_show_persistent_when_no_regressions(self):
        base_meta, base_results = _make_run([_make_result("M", "S", "C", TestOutcome.FAIL, "boom")])
        target_meta, target_results = _make_run([_make_result("M", "S", "C", TestOutcome.FAIL, "boom")])
        args = self.parser.parse_args(["--base", "base", "--target", "target"])

        with mock.patch("arkui_xts_selector.xts_compare.cli.load_run", side_effect=[(base_meta, base_results), (target_meta, target_results)]), \
                mock.patch("arkui_xts_selector.xts_compare.cli.format_report", return_value="ok") as format_report_mock, \
                mock.patch("sys.stdout", new=io.StringIO()):
            code = _run_compare(args)

        self.assertEqual(code, 0)
        self.assertTrue(args.show_persistent)
        self.assertTrue(format_report_mock.call_args.kwargs["show_persistent"])


class PhaseFourTests(unittest.TestCase):
    def setUp(self):
        self.parser = build_parser()

    def test_open_archive_missing_path_raises_file_not_found(self):
        with self.assertRaises(FileNotFoundError):
            open_archive("/definitely/missing/xts.zip")

    def test_failure_type_unknown_alias_is_preserved(self):
        self.assertIs(FailureType.UNKNOWN, FailureType.UNKNOWN_FAIL)
        self.assertEqual(FailureType.UNKNOWN.value, "UNKNOWN")

    def test_load_run_warns_on_duplicate_test_identity(self):
        tmp = tempfile.mkdtemp()
        try:
            report_dir = Path(tmp) / "report"
            report_dir.mkdir()
            (report_dir / "summary_report.xml").write_text(
                """<testsuites name="ActsDup">
<testsuite name="Suite">
  <testcase name="case1" status="run" result="true" />
  <testcase name="case1" status="run" result="false" />
</testsuite>
</testsuites>
""",
                encoding="utf-8",
            )
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter("always")
                load_run(str(report_dir))
            self.assertTrue(any("Duplicate test identity" in str(item.message) for item in caught))
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_main_auto_generates_html_output_path(self):
        tmp = tempfile.mkdtemp()
        try:
            base_dir = Path(tmp) / "base"
            target_dir = Path(tmp) / "target"
            base_dir.mkdir()
            target_dir.mkdir()
            _write_valid_summary_xml(base_dir / "summary_report.xml")
            _write_valid_summary_xml(target_dir / "summary_report.xml")

            stderr = io.StringIO()
            with mock.patch("sys.stdout", new=io.StringIO()), mock.patch("sys.stderr", new=stderr):
                code = main([str(base_dir), str(target_dir), "--html"])

            self.assertEqual(code, 0)
            self.assertIn("HTML output requires a file. Writing to:", stderr.getvalue())
        finally:
            for html_file in Path.cwd().glob("xts_compare_*.html"):
                html_file.unlink(missing_ok=True)
            shutil.rmtree(tmp, ignore_errors=True)

    def test_format_report_regressions_only_shows_only_regression_section(self):
        base_meta, base_results = _make_run(
            [
                _make_result("M", "S", "regression_case", TestOutcome.PASS),
                _make_result("M", "S", "improvement_case", TestOutcome.FAIL, "old"),
            ]
        )
        target_meta, target_results = _make_run(
            [
                _make_result("M", "S", "regression_case", TestOutcome.FAIL, "boom"),
                _make_result("M", "S", "improvement_case", TestOutcome.PASS),
            ]
        )
        report = compare_runs(base_meta, base_results, target_meta, target_results)
        text = format_report(report, regressions_only=True)
        self.assertIn("REGRESSIONS", text)
        self.assertNotIn("IMPROVEMENTS", text)
        self.assertNotIn("Module Health", text)

    def test_format_report_emits_failure_type_tip(self):
        base_meta, base_results = _make_run(
            [
                _make_result("M", "S", "c1", TestOutcome.PASS),
                _make_result("M", "S", "c2", TestOutcome.PASS),
            ]
        )
        target_meta, target_results = _make_run(
            [
                TestResult(
                    identity=TestIdentity("M", "S", "c1"),
                    outcome=TestOutcome.FAIL,
                    message="App died",
                    failure_type=FailureType.CRASH,
                ),
                TestResult(
                    identity=TestIdentity("M", "S", "c2"),
                    outcome=TestOutcome.FAIL,
                    message="App died",
                    failure_type=FailureType.CRASH,
                ),
            ]
        )
        report = compare_runs(base_meta, base_results, target_meta, target_results)
        text = format_report(report)
        self.assertIn("Use --failure-type crash", text)

    def test_format_report_emits_stable_blocked_tip(self):
        base_meta, base_results = _make_run([_make_result("M", "S", "c1", TestOutcome.BLOCKED)])
        target_meta, target_results = _make_run([_make_result("M", "S", "c1", TestOutcome.BLOCKED)])
        report = compare_runs(base_meta, base_results, target_meta, target_results)
        text = format_report(report)
        self.assertIn("Use --show-stable-blocked", text)

    def test_format_report_can_show_stable_blocked_section(self):
        base_meta, base_results = _make_run([_make_result("M", "S", "c1", TestOutcome.BLOCKED)])
        target_meta, target_results = _make_run([_make_result("M", "S", "c1", TestOutcome.BLOCKED)])
        report = compare_runs(base_meta, base_results, target_meta, target_results)
        text = format_report(report, show_stable_blocked=True)
        self.assertIn("STABLE BLOCKED", text)

    def test_main_auto_orders_positional_compare_by_filename_timestamp(self):
        tmp = tempfile.mkdtemp()
        try:
            later_dir = Path(tmp) / "2025-12-25-16-48-38"
            earlier_dir = Path(tmp) / "2025-12-11-17-10-38"
            later_dir.mkdir()
            earlier_dir.mkdir()
            _write_valid_summary_xml(later_dir / "summary_report.xml")
            _write_valid_summary_xml(earlier_dir / "summary_report.xml")

            stdout = io.StringIO()
            stderr = io.StringIO()
            with mock.patch("sys.stdout", new=stdout), mock.patch("sys.stderr", new=stderr):
                code = main([str(later_dir), str(earlier_dir)])

            self.assertEqual(code, 0)
            self.assertIn("Auto-detected compare order", stderr.getvalue())
            self.assertIn("2025-12-11-17-10-38", stdout.getvalue())
            self.assertIn("2025-12-25-16-48-38", stdout.getvalue())
        finally:
            shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    unittest.main()
